version: '3'

services:
  web:
    build:
      context: ../../
      dockerfile: docker/multi-process/Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      # - DATABASE_INITIAL_CONNECT_MAX_RETRIES=5
      - INTENTIONALLY_SLEEP=10
    env_file:
      - ../mysql.env
      - ../secrets.env
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
