version: '3'

services:
  mysql:
    image: mysql:5.7
    restart: always
    env_file:
      - ../mysql.env
    volumes:
      - mysql:/var/lib/mysql

  web:
    build:
      context: ../../
      dockerfile: docker/single-process/Dockerfile
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ../mysql.env
      - ../secrets.env
    depends_on:
      - mysql

  threaded:
    build:
      context: ../../
      dockerfile: docker/single-process/Dockerfile
    command: /scripts/init bin/threaded.rb
    restart: always
    env_file:
      - ../mysql.env
      - ../secrets.env
    depends_on:
      - mysql
      - web

volumes:
  mysql:
