version: '3'

services:
  postgres:
    image: postgres:9.5
    restart: always
    env_file:
      - ../postgres.env
    volumes:
      - postgres:/var/lib/postgresql/data

  web:
    image: huginn/huginn-single-process
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ../postgres.env
      - ../secrets.env
    depends_on:
      - postgres

  threaded:
    image: huginn/huginn-single-process
    command: /scripts/init bin/threaded.rb
    restart: always
    env_file:
      - ../postgres.env
      - ../secrets.env
    depends_on:
      - postgres
      - web

volumes:
  postgres:
